version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker build -t php-base-image:latest .
      - docker tag php-base-image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/planet-cargo-base-php:latest
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/planet-cargo-base-php:latest
