version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login)
  build:
    commands:
      - docker build -t php-base-image:latest .
      - docker tag php-base-image:latest 323441517494.dkr.ecr.eu-west-2.amazonaws.com/planet-cargo-base-php:latest
  post_build:
    commands:
      - docker push 323441517494.dkr.ecr.eu-west-2.amazonaws.com/planet-cargo-base-php:latest
