Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: php-base-image
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: CodeBuildAccess
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
#      LifecyclePolicy:
#        LifecyclePolicyText: |
#          {
#            "rules": [
#                {
#                    "rulePriority": 1,
#                    "description": "Expire images older than 60 days",
#                    "selection": {
#                        "tagStatus": "untagged",
#                        "countType": "sinceImagePushed",
#                        "countUnit": "days",
#                        "countNumber": 60
#                    },
#                    "action": {
#                        "type": "expire"
#                    }
#                }
#            ]
#          }

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "cloudformation.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - ecs:*
                  - ecr:*
                  - iam:*
